version: "3"

services:
  app:
    build: docker/php
    volumes:
      - ./:/app

  nginx:
    image: nginx:1.12-alpine
    ports:
      - "8080:80"
    #      - 443:443
    volumes:
      - ./:/app
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
    depends_on:
      - app
#  db:
#    build: docker/pgsql
#    ports:
#      - 5432:5432
#    environment:
#      - POSTGRES_DB=blackterminal
#      - POSTGRES_USER=blackterminal
#      - POSTGRES_PASSWORD=1234
#    volumes:
#      - ./docker/pgsql:/var/www/html/db
#    networks:
#      static-network:
#        ipv4_address: 170.20.0.5


