version: '3'
services:
#  nginx:
#    # используем последний стабильный образ nginx
#    image: nginx:latest
#    # маршрутизируем порты
#    ports:
#      - "80:80"
#    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
#    volumes:
#      - ./docker/nginx/host:/etc/nginx/conf.d
#      - ./docker/nginx/www:/var/www
#      - ./docker/nginx/logs:/var/log/nginx
#    # nginx должен общаться с php контейнером
#    links:
#      - app

  app:
    build:
      context: docker/php
    ports:
      - "8080:9000"
    volumes:
      - .:/var/www