version: "3"

services:
  app:
    build: docker/php
    volumes:
      - ./:/app

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    #      - 443:443
    volumes:
      - ./:/app
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
    depends_on:
      - app
    links:
      - db

  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/www/html/db
#    volumes:
#      - /etc/mysql:/etc/mysql
#      - ./logs/mysql:/var/log/mysql
#      - ./mysql:/var/lib/mysql
#      - ./mysql-files:/var/lib/mysql-files
#      - ./data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: soundcloudparser

